language: node_js
node_js:
  - "10.8.0"
install:
  - npm install
  
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

  - npm run mig-test
 
script:
 - npm test

after_script:
   - npm run coverage
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- npm run coverage

